spring.application.name=api_rfind

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql = true

# Porta serial
serial.port=${SERIAL_PORT} 

serial.baudrate=9600

# Habilita debug
logging.level.org.springframework.web=DEBUG
logging.level.com.rfindapi=DEBUG

# Tamanho máximo para mensagens seriais
serial.buffer.size=1024
